---
title: 手写Promise
date: 2021-04-15
tags:
 - JS异步编程
categories: 
 - JS异步编程
---

# 手写Promise


> 1. Promise 就是一个类, 在执行这个类的时候, 需要传递一个执行器进去, 执行器会立即执行
> 2. Promise 中有三种状态 分别成为 成功 fulfilled 失败, rejected 等待 pending
>   pending => fulfilled
>   pending => rejected
>   状态只能改变一次, 确定了就不能改了
> 3. resolve 和 reject 函数是用来更改状态的
>       resolve: fulfilled
>       reject: rejected
> 4. then方法中做的事情就是判断状态，如果状态是成功， 就调用成功的回调，如果是失败，就调用失败的回调
> 5. then成功回调有一个参数, 表示成功的值, 失败后有一个参数, 表示失败的原因
> 6. promise的then方法是多次调用的
> 7. promise的then应该返回一个新的promise
> 8. promise.all传入一组数组, 如果全部成功, 则按顺序(数组顺序)返回执行结果数组, 如果有一个失败, 则返回失败原因
> 9. promise.race传入一组数组, 其中最先执行完的直接返回, 无论对错
> 10. promise.allsettled传入一组数组, 无状态返回执行结果, 无论对错, 都装在一个数组里面, 每一个数组成员都有自己的状态

```javaScript
const PENDING = "pending"; // 进行中
const FULFILLED = "fulfilled"; // 成功
const REJECTED = "rejected" // 失败

class MyPromise {
    constructor(executor) {
        try {
            executor(this.resolve, this.reject);
        } catch (e) {
            this.reject(e)
        }
         // 这个执行器代表那个回调函数, 这个执行器是立即执行的
    }

    state = PENDING;

    // * 成功之后的值
    value = undefined;

    // * 失败的原因
    reason = undefined;

    // * 成功回调, 因为不止then一次, 同一个promise实例下的then可以多次调用, 因此他不应该是一个定值, 而是一个数组
    successCallback = [];
    // * 失败回调
    failCallback = [];

    // * 为什么要使用箭头函数，就是因为调用resolve的时候是直接调用的，如果不是箭头函数，那就容易出现函数内部有this指向undefined
    // * 使用箭头函数他就指向promise对象
    // * 不用箭头函数就要去 constructor 中一个一个 bind
    resolve = (value) => {
        // 修改状态
        if (this.state === PENDING) {
            // 因为只有状态是pending才能更改, 防止二次修改
            this.state = FULFILLED;
            this.value = value;
            // this.successCallback.map(fn => fn(value));
            while(this.successCallback.length) {
                // 清空长度, 同时先进去的先执行(先进先出， 队列)
                this.successCallback.shift()();
            }
        }
    }

    reject = (reason) => {
        if (this.state === PENDING) {
            this.state = REJECTED;
            this.reason = reason;
            // this.failCallback.map(fn => fn(reason));
            while(this.failCallback.length) { // 这一的话保证有才执行，虽然上面的也可以
                this.failCallback.shift()();
            }
        }
    }

    // then一般是原型链上调用，不是类就是实例在then，因此可以拿到this不需要使用箭头函数
    then (successCallback, failCallback) {
        // then中的方法应该是可选参数, 并且只能是函数, 如果不是就转换成函数
        successCallback = typeof successCallback === 'function' ? successCallback : v => v;
        failCallback = typeof failCallback === 'function' ? failCallback : err => new Error(err);
        let promise2 = new MyPromise((resolve, reject) => {
            if (this.state === FULFILLED) {
                queueMicrotask(() => {
                    try {
                        let x = successCallback(this.value);
                        // TODO 由于目前还拿不到promise2, 因此要先让内部代码都变成异步才行
                        this.resolvePromise(promise2, x, resolve, reject);
                    } catch (e) {
                        reject(e)
                    }
                })
            } else if (this.state === REJECTED) {
                queueMicrotask(() => {
                    try {
                        let x = failCallback(this.reason);
                        this.resolvePromise(promise2, x, resolve, reject);
                    } catch (e) {
                        reject(e)
                    }
                })
            } else {
                // 将成功回调和失败回调存储起来
                this.successCallback.push(() => {
                    queueMicrotask(() => {
                        try {
                            let x = successCallback(this.value);
                            this.resolvePromise(promise2, x, resolve, reject);
                        } catch (e) {
                            reject(e)
                        }
                    })
                });
                this.failCallback.push(() => {
                    queueMicrotask(() => {
                        try {
                            let x = failCallback(this.reason);
                            this.resolvePromise(promise2, x, resolve, reject);
                        } catch (e) {
                            reject(e)
                        }
                    })
                });
            }
        });
        return promise2;
    }

    // 用于解析promise
    resolvePromise(promise2, x, resolve, reject) {
        // TODO 判断 x 的值是普通值还是promise对象
        // TODO 如果是普通值, 就直接调用 resolve
        // TODO 如果是promise对象, 查看promise对象返回的结果
        // TODO 在根据promise对象返回的结果, 决定调用resolve还是调用reject
        // TODO 由于这个东西会经常复用, 因此我们应该抽出一个新的函数来
        // TODO 但是不允许返回一个then方法本身的promise对象, 否则会发生循环引用报错
        // ! 因此第一步就判断是否自己返回自己, 返回就报错
        if (promise2 === x) {
            return reject(new TypeError('Chaining cycle detected for promise #<Promise>'));
        }
        if (x instanceof MyPromise) {
            // promise对象
            // x.then((value) => resolve(value), reject => reject(reason))
            // 简化一下如下
            x.then(resolve, reject);
        } else {
            // 普通值
            resolve(x)
        }
    }

    static all(promiseArr) {
        let res = [];
        let index = 0;
        function addData (key, value, resolve) {
            res[key] = value;
            index++; // 为了消除异步没有执行完就返回的问题
            if (index === promiseArr.length) {
                // * 所有的异步操作最终都要执行addData, 因此走到这里, 一定是已经走完了所有的promise异步操作
                resolve(res);
            }
        }
        return new MyPromise((resolve, reject) => {
            for (let i = 0; i < promiseArr.length; i++) {
                let current = promiseArr[i];
                if (current instanceof MyPromise) {
                    // TODO Promise对象
                    current.then(value => addData(i, value, resolve), (err) => {
                        reject(err)
                    })
                } else {
                    // TODO 普通值
                    addData(i, current, resolve)
                }
            }
        })
    }

    static race(promiseAll) {
        let res = undefined;
        function addData (value, resolve) {
            res = value;
            resolve(res)
        }
        return new Promise((resolve, reject) => {
            for (let i = 0; i < promiseAll.length; i++) {
                const current = promiseAll[i]
                if (current instanceof MyPromise) {
                    current.then(value => addData(value, resolve), err => {
                        reject(err);
                    })
                } else {
                    addData(current, resolve);
                }
            }
        })
    }

    static allSettled(promiseALl) {
        let res = [];
        let index = 0;
        let addData = function(key, value, resolve, status) {
            if (status === RESOLVED) {
                res[key] = {
                    status: 'fulfilled',
                    value: value
                }
            } else {
                res[key] = {
                    status: 'rejected',
                    reason: value
                }
            }
            index++;
            if (index === promiseArr.length) {
                // * 说明执行完了, 此时执行resolve
                resolve(res);
            }
        }
        return new MyPromise((resolve, reject) => {
            for (let i = 0; i < promiseArr.length; i++) {
                const current = promiseArr[i];
                if (current instanceof MyPromise) {
                    // * 当前值是promise
                    current.then(value => addData(i, value, resolve, RESOLVED), err => {
                        // * 有错误也添加到数组中, 无状态返回一组执行结果数组
                        addData(i, value, resolve, REJECTED);
                    });
                } else {
                    // * 普通值
                    addData(i, current, resolve, RESOLVED);
                }
            }
        })
    }

    static resolve (value) {
        if (value instanceof MyPromise) return;
        return new MyPromise(resolve => resolve(value));
    }

    finally (callback) {
        // 第一都要执行callback
        // 第二返回的是一个promise对象, 后面在then一次可以拿到promise对象最终返回的结果
        return this.then((value) => {
            return MyPromise.resolve(callback()).then(() => value);
        }, (err) => {
            return MyPromise.resolve(callback()).then(() => {throw err});
        })
    }

    catch (callback) {
        return this.then(undefined, callback);
    }
}
```